SUPPORTED_LANGUAGES = (
    ('.properties', 'properties'),
    ('Apache config', 'apache'),
    ('Bash', 'bash'),
    ('C', 'c'),
    ('C#', 'cs'),
    ('C++', 'cpp'),
    ('C-like foundation grammar for C/C++ grammars', 'c-like'),
    ('CSS', 'css'),
    ('Diff', 'diff'),
    ('Go', 'go'),
    ('HTML / XML', 'xml'),
    ('CoffeeScript', 'coffee'),
    ('JSON', 'json'),
    ('Java', 'java'),
    ('JavaScript', 'javascript'),
    ('Kotlin', 'kotlin'),
    ('Less', 'less'),
    ('Lua', 'lua'),
    ('Makefile', 'makefile'),
    ('Markdown', 'markdown'),
    ('Nginx config', 'nginx'),
    ('Objective-C', 'mm'),
    ('PHP', 'php'),
    ('Perl', 'perl'),
    ('Plain text', 'txt'),
    ('Python', 'python'),
    ('Python REPL', 'pycon'),
    ('Ruby', 'ruby'),
    ('Rust', 'rust'),
    ('SCSS', 'scss'),
    ('SQL', 'sql'),
    ('Shell', 'shell'),
    ('Swift', 'swift'),
    ('TOML', 'toml'),
    ('TypeScript', 'typescript'),
    ('YAML', 'yaml'),
)
